# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('cargo', models.CharField(max_length=120, verbose_name='cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(max_length=8, verbose_name='cnh')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('categoria', models.CharField(max_length=2, verbose_name='categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=250, verbose_name='origem')),
                ('destino', models.CharField(max_length=250, verbose_name='destino')),
                ('data', models.DateTimeField(verbose_name='data')),
                ('Funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, verbose_name='placa')),
                ('marca', models.CharField(max_length=20, verbose_name='marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo')),
                ('ano', models.CharField(max_length=4, verbose_name='ano')),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='Motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Motorista'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='Solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Solicitacao'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='Veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Veiculo'),
        ),
    ]
