# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_solicitacao_atendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao_atendimento',
            name='Atendimento',
        ),
        migrations.RemoveField(
            model_name='solicitacao_atendimento',
            name='Solicitacao',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=8, verbose_name='placa'),
        ),
        migrations.DeleteModel(
            name='Solicitacao_Atendimento',
        ),
    ]
